java_library(
  name = "stilltasty",
  srcs = glob(["**/*.java"]),
  visibility = ["//visibility:public"],
  deps = [
    "//third_party:org_jsoup_jsoup",
    "//third_party:org_apache_httpcomponents_httpclient",
  ],
)
