#!/bin/bash

silence () {
    "$@" &>/dev/null
}

fail () {
    echo "failed!"
    exit $1
}

echo -n "Stashing unstaged, untracked files... "
silence git stash -k -u && echo "done." || fail 1

echo "Running tests..."
rake test

test_run_ret=$?

echo -n "Restoring working dir... "
silence git stash pop && echo "done." || fail 0
exit $test_run_ret
