#!/bin/bash

silence () {
    "$@" &>/dev/null
}

fail () {
    echo "failed!"
    exit $1
}

echo -n "Stashing unstaged, untracked files... "
silence git stash -k -u && echo "done." || fail 1

echo "Running PEP8 checks..."
pep8 --ignore E501 scripts shelf

pep8_ret=$?

echo -n "Restoring working dir... "
silence git stash pop && echo "done." || fail 0
exit $pep8_ret
