#!/bin/bash

server=$1
OUTPUT="fixtures/scrape.json"

ping () {
    curl -s $server
    ret=$?
    if [[ 0 != $ret ]]; then
        echo "Could not connect to server"
        exit $ret
    fi
}

if [[ "" = $server ]]; then
    echo "usage: scrape [server]"
    exit 1
fi

ping

seq 18000 19000 | xargs -I{} sh -c "curl -s $server/items/{}; echo" | grep -v ": 404" | tee $OUTPUT
